---
- name: Copy Application folders to Deployments folder
  shell: "rsync -ar {{ old_instance_path }}/standalone/deployments/ --exclude=*.deployed --exclude=*.failed {{ instance_path }}/standalone/deployments/"

- name: Deploy Applications
  shell: find /opt/wf18-"{{ server_instance }}"/standalone/deployments/ -maxdepth 1 -type d -exec touch {}.dodeploy \;

#- name: Deploy Applications
#  copy:
#    content: ""
#    force: no
#    dest: "/opt/wf18-{{ server_instance }}/standalone/deployments/{{ item }}.dodeploy"
#  with_filetree: "/opt/wf18-{{ server_instance }}/standalone/deployments/"
#  when: item.state == 'directory' 
...
